// Equivalence + generation harness for bench/flight.
// 1. Calibrates the same way `struktura generate-hybrid` does (2048 samples,
//    seed 424242, synth_spacecraft), emits hybrid_monitor.c.
// 2. Runs a second, longer stream with an injected stuck-sensor fault
//    through the Rust HybridMonitor, and writes every alarm tick
//    (t, channel, leg) to alarms_rust.csv — this is compared against the
//    ARM-emulated C monitor's output for the same stream.
// 3. Also writes the raw stream to stream.csv (one row per tick, one column
//    per channel) so the C harness can replay exactly the same input.

use struktura::codegen::generate_hybrid_c;
use struktura::monitor::HybridMonitor;
use struktura::telemetry_bench::synth_spacecraft;
use std::fs;
use std::io::Write;

fn leg_name(leg: struktura::monitor::Leg) -> &'static str {
    use struktura::monitor::Leg::*;
    match leg {
        Residual => "RESIDUAL",
        RepeatedValue => "REPEATED",
        Dfa => "DFA",
        LevelShift => "LEVEL",
        ResidualCusum => "CUSUM",
        Missingness => "MISSINGNESS",
        Parity => "PARITY",
    }
}

fn main() {
    let out_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("..");

    // 1. Calibrate + generate C, matching `struktura generate-hybrid` defaults.
    let calib = synth_spacecraft(2048, 424242);
    let mon0 = HybridMonitor::calibrate(&calib).expect("calibration failed");
    let code = generate_hybrid_c(&mon0.export());
    fs::write(out_dir.join("hybrid_monitor.c"), &code).expect("write C");
    println!(
        "generated hybrid_monitor.c: {} channels, {} bytes",
        mon0.channels(),
        code.len()
    );

    // 2. Deterministic evaluation stream with an injected stuck-sensor fault,
    //    same shape as struktura's own self-test (freeze one channel).
    let n = 3000usize;
    let mut stream = synth_spacecraft(n, 909090);
    let nch = stream.len();
    let repeat_ch = mon0
        .export()
        .channels
        .iter()
        .position(|c| c.repeat_enabled)
        .unwrap_or(0);
    // Freeze the repeat-enabled channel from the stream's midpoint onward.
    let freeze_t = n / 2;
    let freeze_val = stream[repeat_ch][freeze_t];
    for t in freeze_t..n {
        stream[repeat_ch][t] = freeze_val;
    }

    // Write stream.csv: one row per tick, columns = channels.
    let mut sc = fs::File::create(out_dir.join("stream.csv")).unwrap();
    for t in 0..n {
        let row: Vec<String> = (0..nch).map(|c| format!("{:.17e}", stream[c][t])).collect();
        writeln!(sc, "{}", row.join(",")).unwrap();
    }

    // Also embed the stream as a static C array (stream_data.h) so the
    // bare-metal ARM harness can replay it with no filesystem/semihosting
    // file I/O required — only stdout via semihosting.
    let mut hdr = fs::File::create(out_dir.join("stream_data.h")).unwrap();
    writeln!(hdr, "/* generated by genrs: {} ticks x {} channels */", n, nch).unwrap();
    writeln!(hdr, "#define STREAM_N   {}", n).unwrap();
    writeln!(hdr, "#define STREAM_CH  {}", nch).unwrap();
    writeln!(hdr, "static const double STREAM[STREAM_N][STREAM_CH] = {{").unwrap();
    for t in 0..n {
        let row: Vec<String> = (0..nch).map(|c| format!("{:.17e}", stream[c][t])).collect();
        writeln!(hdr, "    {{ {} }},", row.join(", ")).unwrap();
    }
    writeln!(hdr, "}};").unwrap();

    // 3. Replay through the Rust monitor (fresh instance, same calibration),
    //    recording every alarm tick.
    let mut mon = HybridMonitor::calibrate(&calib).expect("calibration failed");
    let mut alarms = fs::File::create(out_dir.join("alarms_rust.csv")).unwrap();
    writeln!(alarms, "t,leg").unwrap();
    let mut sample = vec![0.0f64; nch];
    let mut fired = false;
    for t in 0..n {
        for c in 0..nch {
            sample[c] = stream[c][t];
        }
        if let Some(leg) = mon.push(&sample) {
            writeln!(alarms, "{},{}", t, leg_name(leg)).unwrap();
            fired = true;
            break; // C monitor also latches after first alarm.
        }
    }
    if !fired {
        println!("NOTE: rust monitor never alarmed over {} ticks", n);
    }
    println!("wrote stream.csv ({} ticks x {} ch), alarms_rust.csv", n, nch);
}
