/*******************************************************************************
** File: dfa_monitor_cfs.c
**
** Purpose:
**   DFA structural health monitor for cFS.
**   Custom ogma template: replaces Copilot temporal monitors with DFA
**   scaling analysis. Detects behavioral degradation before thresholds fire.
**
**   Generated by: ogma cfs --template-dir struktura-dfa-template ...
**   Algorithm:    Peng et al., Physical Review E 49(2), 1994
**   Library:      https://github.com/koscak-labs/struktura
**
*******************************************************************************/

#include "dfa_monitor_cfs.h"
#include "dfa_monitor_cfs_perfids.h"
#include "dfa_monitor_cfs_msgids.h"
#include "dfa_monitor_cfs_msg.h"
#include "dfa_monitor_cfs_events.h"
#include "dfa_monitor_cfs_version.h"
#include "dfa_core.h"
{{#impl_extra_header}}
{{{.}}}
{{/impl_extra_header}}

/*
** DFA monitor state per channel
*/
#ifndef DFA_WINDOW_SIZE
#define DFA_WINDOW_SIZE 256
#endif

#ifndef DFA_THRESHOLD
#define DFA_THRESHOLD 0.08
#endif

#ifndef DFA_LEARN_WINDOWS
#define DFA_LEARN_WINDOWS 10
#endif

#ifndef DFA_R2_MIN
#define DFA_R2_MIN 0.7
#endif

typedef struct {
    double buffer[DFA_WINDOW_SIZE];
    uint32 pos;
    uint32 filled;
    double baseline_alpha;
    uint8  baseline_set;
    uint32 window_count;
} dfa_channel_t;

{{#variables}}
{{varDeclType}} {{varDeclName}};
{{/variables}}

/*
** One DFA channel per monitored variable
*/
{{#variables}}
static dfa_channel_t dfa_ch_{{varDeclName}};
{{/variables}}

/*
** global data
*/
dfa_monitor_hk_tlm_t    DFA_MONITOR_HkTelemetryPkt;
CFE_SB_PipeId_t         DFA_MONITOR_CommandPipe;
CFE_MSG_Message_t      *DFA_MONITORMsgPtr;
CFE_SB_Buffer_t        *SBBufPtr;

static CFE_EVS_BinFilter_t DFA_MONITOR_EventFilters[] = {
    {DFA_MONITOR_STARTUP_INF_EID,       0x0000},
    {DFA_MONITOR_COMMAND_ERR_EID,       0x0000},
    {DFA_MONITOR_BASELINE_INF_EID,      0x0000},
    {DFA_MONITOR_SHIFT_ERR_EID,         0x0000},
    {DFA_MONITOR_INSUFFICIENT_INF_EID,  0x0000},
};

static void dfa_channel_init(dfa_channel_t *ch) {
    memset(ch, 0, sizeof(*ch));
}

static int dfa_channel_push(dfa_channel_t *ch, double value,
                            const char *name) {
    ch->buffer[ch->pos] = value;
    ch->pos = (ch->pos + 1) % DFA_WINDOW_SIZE;
    if (ch->pos == 0) ch->filled = 1;
    if (!ch->filled) return 0;

    ch->window_count++;
    dfa_result_t r = dfa_compute(ch->buffer, DFA_WINDOW_SIZE);

    if (!ch->baseline_set &&
        ch->window_count >= DFA_LEARN_WINDOWS &&
        r.r_squared > DFA_R2_MIN) {
        ch->baseline_alpha = r.alpha;
        ch->baseline_set = 1;
        CFE_EVS_SendEvent(DFA_MONITOR_BASELINE_INF_EID,
            CFE_EVS_EventType_INFORMATION,
            "DFA baseline for %s: alpha=%.3f R2=%.4f",
            name, r.alpha, r.r_squared);
        return 0;
    }
    if (!ch->baseline_set) return 0;

    if (r.r_squared < DFA_R2_MIN) {
        CFE_EVS_SendEvent(DFA_MONITOR_INSUFFICIENT_INF_EID,
            CFE_EVS_EventType_INFORMATION,
            "DFA %s: R2=%.4f below threshold, skipping", name, r.r_squared);
        return 0;
    }

    double shift = fabs(r.alpha - ch->baseline_alpha);
    if (shift >= DFA_THRESHOLD) {
        int severity = (shift >= DFA_THRESHOLD * 1.875) ? 4 : 3;
        CFE_EVS_SendEvent(DFA_MONITOR_SHIFT_ERR_EID,
            CFE_EVS_EventType_ERROR,
            "DFA structural shift on %s: alpha=%.3f baseline=%.3f "
            "delta=%.3f severity=%d",
            name, r.alpha, ch->baseline_alpha,
            r.alpha - ch->baseline_alpha, severity);
        return severity;
    }
    return 1;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
void DFA_MONITOR_AppMain(void)
{
    CFE_Status_t status;
    uint32 RunStatus = CFE_ES_RunStatus_APP_RUN;

    CFE_ES_PerfLogEntry(DFA_MONITOR_CFS_PERF_ID);
    status = DFA_MONITOR_AppInit();

    if (status != CFE_SUCCESS)
        RunStatus = CFE_ES_RunStatus_APP_ERROR;

    while (CFE_ES_RunLoop(&RunStatus) == true)
    {
        CFE_ES_PerfLogExit(DFA_MONITOR_CFS_PERF_ID);
        status = CFE_SB_ReceiveBuffer(&SBBufPtr, DFA_MONITOR_CommandPipe, 500);
        CFE_ES_PerfLogEntry(DFA_MONITOR_CFS_PERF_ID);

        if (status == CFE_SUCCESS)
            DFA_MONITOR_ProcessCommandPacket();
    }

    CFE_ES_PerfLogExit(DFA_MONITOR_CFS_PERF_ID);
    CFE_ES_ExitApp(RunStatus);
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
CFE_Status_t DFA_MONITOR_AppInit(void)
{
    CFE_Status_t status;

    status = CFE_EVS_Register(DFA_MONITOR_EventFilters,
                 sizeof(DFA_MONITOR_EventFilters)/sizeof(CFE_EVS_BinFilter_t),
                 CFE_EVS_EventFilter_BINARY);

    if (status != CFE_SUCCESS) {
        CFE_ES_WriteToSysLog("DFA Monitor: Error Registering Events, "
                             "RC = 0x%08lX\n", (unsigned long)status);
        return status;
    }

    status = CFE_SB_CreatePipe(&DFA_MONITOR_CommandPipe,
                               DFA_MONITOR_PIPE_DEPTH,
                               "DFA_MONITOR_CMD_PIPE");
    if (status != CFE_SUCCESS) {
        CFE_EVS_SendEvent(DFA_MONITOR_CR_PIPE_ERR_EID,
            CFE_EVS_EventType_ERROR,
            "DFA Monitor: Error creating pipe, RC = 0x%08lX",
            (unsigned long)status);
        return status;
    }

    {{#msgIds}}
    status = CFE_SB_Subscribe(CFE_SB_ValueToMsgId({{.}}),
                              DFA_MONITOR_CommandPipe);
    if (status != CFE_SUCCESS) {
        CFE_EVS_SendEvent(DFA_MONITOR_CR_SUB_ERR_EID,
            CFE_EVS_EventType_ERROR,
            "DFA Monitor: Error subscribing, RC = 0x%08lX",
            (unsigned long)status);
        return status;
    }
    {{/msgIds}}

    {{#variables}}
    dfa_channel_init(&dfa_ch_{{varDeclName}});
    {{/variables}}

    CFE_EVS_SendEvent(DFA_MONITOR_STARTUP_INF_EID,
        CFE_EVS_EventType_INFORMATION,
        "DFA Monitor App Initialized. Window=%d Threshold=%.3f "
        "Version %d.%d.%d.%d",
        DFA_WINDOW_SIZE, DFA_THRESHOLD,
        DFA_MONITOR_CFS_MAJOR_VERSION, DFA_MONITOR_CFS_MINOR_VERSION,
        DFA_MONITOR_CFS_REVISION, DFA_MONITOR_CFS_MISSION_REV);

    return CFE_SUCCESS;
}

/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */
void DFA_MONITOR_ProcessCommandPacket(void)
{
    {{#msgCases}}
    static CFE_SB_MsgId_t {{msgInfoId}}_s = CFE_SB_MSGID_RESERVED;
    {{/msgCases}}

    CFE_SB_MsgId_t MsgId = CFE_SB_INVALID_MSG_ID;

    {{#msgCases}}
    if (!CFE_SB_IsValidMsgId({{msgInfoId}}_s))
        {{msgInfoId}}_s = CFE_SB_ValueToMsgId({{msgInfoId}});
    {{/msgCases}}

    CFE_MSG_GetMsgId(&SBBufPtr->Msg, &MsgId);

    {{#msgCases}}
    if (CFE_SB_MsgId_Equal(MsgId, {{msgInfoId}}_s))
    {
        DFA_MONITORMsgPtr = &SBBufPtr->Msg;
        DFA_MONITOR_Process{{msgInfoDesc}}();
        return;
    }
    {{/msgCases}}

    DFA_MONITOR_HkTelemetryPkt.dfa_monitor_command_error_count++;
    CFE_EVS_SendEvent(DFA_MONITOR_COMMAND_ERR_EID,
        CFE_EVS_EventType_ERROR,
        "DFA_MONITOR: invalid command packet, MID = 0x%x",
        CFE_SB_MsgIdToValue(MsgId));
}

{{#msgHandlers}}
void DFA_MONITOR_Process{{msgDataDesc}}(void)
{
    {{#msgDataFromType}}
    {{msgDataFromType}}* msg;
    msg = ({{.}}*) DFA_MONITORMsgPtr;
    {{/msgDataFromType}}
    {{^msgDataFromType}}
    {{msgDataVarType}}* msg;
    msg = ({{msgDataVarType}}*) DFA_MONITORMsgPtr;
    {{/msgDataFromType}}
    {{#msgDataFromField}}
    {{msgDataVarName}} = msg->{{.}};
    {{/msgDataFromField}}
    {{^msgDataFromField}}
    {{msgDataVarName}} = *msg;
    {{/msgDataFromField}}

    {{#msgDataActive}}
    dfa_channel_push(&dfa_ch_{{msgDataVarName}},
                     (double){{msgDataVarName}},
                     "{{msgDataVarName}}");
    {{/msgDataActive}}
}

{{/msgHandlers}}
