/* dfa_core.h -- Self-contained DFA structural health monitor
 * Generated by Struktura for ogma integration.
 * Zero dependencies. Pre-80s discipline.
 * https://github.com/koscak-labs/struktura
 *
 * DFA_BOXES below is struktura::dfa_box_sizes(256) -- correct for the
 * default DFA_WINDOW_SIZE (256) only. If you override DFA_WINDOW_SIZE
 * (via extra-vars or a -D flag), regenerate this table for your window:
 * `struktura generate --cfs --window <N> -o /tmp/x` and copy its
 * fsw/src/dfa_core.h DFA_BOXES/DFA_NUM_BOXES/DFA_BOX_SLOTS, or call
 * struktura::dfa_box_sizes(<N>) directly. A mismatched table (as this file
 * carried before this fix -- a fixed {16,24,36,54,81,121} that never
 * matched Rust's dfa_box_sizes at any window) makes this C's alpha diverge
 * from struktura's own Rust dfa().
 */

#ifndef DFA_CORE_H
#define DFA_CORE_H

#include <math.h>
#include <string.h>

#ifndef DFA_WINDOW_SIZE
#define DFA_WINDOW_SIZE 256
#endif

#define DFA_NUM_BOXES 12
#define DFA_BOX_SLOTS 12

static const int DFA_BOXES[DFA_BOX_SLOTS] = {16, 18, 20, 23, 26, 30, 34, 38, 43, 49, 56, 64};

typedef struct {
    double alpha;
    double r_squared;
} dfa_result_t;

/* `values` is overwritten with the cumulative profile in place (the caller
 * passes its own `ordered` scratch, rebuilt from the ring on every push and
 * not read again afterward, so this avoids a second DFA_WINDOW_SIZE-sized
 * array on the stack). */
static dfa_result_t dfa_compute(double *values, int n) {
    dfa_result_t result = {0.5, 0.0};
    if (n < 64) return result;

    double mean = 0.0;
    int i, seg, b;
    for (i = 0; i < n; i++) mean += values[i];
    mean /= (double)n;

    double cum = 0.0, ss = 0.0;
    for (i = 0; i < n; i++) {
        cum += values[i] - mean;
        values[i] = cum;
        ss += cum * cum;
    }
    /* A box whose F is at most 1e-12 of the profile's RMS measures only
       rounding (a box inside a constant run) and gives no point of the fit,
       as struktura's FLAT_BOX_REL. */
    double floor2 = 1e-12 * 1e-12 * (ss / (double)n);

    double log_s[DFA_BOX_SLOTS], log_f[DFA_BOX_SLOTS];
    int pts = 0;

    for (b = 0; b < DFA_NUM_BOXES && DFA_BOXES[b] <= n / 4; b++) {
        int s = DFA_BOXES[b];
        int num_segs = n / s;
        if (num_segs == 0) continue;
        double f2_sum = 0.0;
        for (seg = 0; seg < num_segs; seg++) {
            int start = seg * s;
            double sx = 0, sy = 0, sxy = 0, sx2 = 0;
            for (i = 0; i < s; i++) {
                double xi = (double)i;
                sx += xi;
                sy += values[start + i];
                sxy += xi * values[start + i];
                sx2 += xi * xi;
            }
            double k = (double)s;
            double det = k * sx2 - sx * sx;
            if (fabs(det) < 1e-15) continue;
            double a0 = (sx2 * sy - sx * sxy) / det;
            double a1 = (k * sxy - sx * sy) / det;
            double resid = 0.0;
            for (i = 0; i < s; i++) {
                double d = values[start + i] - (a0 + a1 * (double)i);
                resid += d * d;
            }
            f2_sum += resid / k;
        }
        double f2 = f2_sum / (double)num_segs;
        if (f2 > floor2) {
            log_s[pts] = log((double)s);
            log_f[pts] = log(sqrt(f2));
            pts++;
        }
    }

    if (pts < 3) return result;

    double k = (double)pts;
    double sx = 0, sy = 0, sxy = 0, sx2 = 0;
    for (i = 0; i < pts; i++) {
        sx += log_s[i]; sy += log_f[i];
        sxy += log_s[i] * log_f[i]; sx2 += log_s[i] * log_s[i];
    }
    double slope = (k * sxy - sx * sy) / (k * sx2 - sx * sx);
    double ic = (sy - slope * sx) / k;
    double ym = sy / k;
    double sst = 0, ssr = 0;
    for (i = 0; i < pts; i++) {
        sst += (log_f[i] - ym) * (log_f[i] - ym);
        ssr += (log_f[i] - slope * log_s[i] - ic) * (log_f[i] - slope * log_s[i] - ic);
    }
    result.alpha = slope;
    result.r_squared = 1.0 - ssr / (sst > 1e-15 ? sst : 1e-15);
    return result;
}

#endif /* DFA_CORE_H */
