/* dfa_core.h -- Self-contained DFA structural health monitor
 * Generated by Struktura for ogma integration.
 * Zero dependencies. Pre-80s discipline.
 * https://github.com/koscak-labs/struktura
 */

#ifndef DFA_CORE_H
#define DFA_CORE_H

#include <math.h>
#include <string.h>

#define DFA_NUM_BOXES 6

static const int DFA_BOXES[DFA_NUM_BOXES] = {16, 24, 36, 54, 81, 121};

typedef struct {
    double alpha;
    double r_squared;
} dfa_result_t;

static dfa_result_t dfa_compute(const double *values, int n) {
    dfa_result_t result = {0.5, 0.0};
    if (n < 64) return result;

    double mean = 0.0;
    int i, seg, b;
    for (i = 0; i < n; i++) mean += values[i];
    mean /= (double)n;

    /* Stack buffer sized to match the monitor's configured window.
     * DFA_WINDOW_SIZE is defined by the ogma template via extra-vars. */
#ifndef DFA_WINDOW_SIZE
#define DFA_WINDOW_SIZE 256
#endif
    double y[DFA_WINDOW_SIZE];
    double cum = 0.0;
    int nn = n > DFA_WINDOW_SIZE ? DFA_WINDOW_SIZE : n;
    for (i = 0; i < nn; i++) {
        cum += values[i] - mean;
        y[i] = cum;
    }

    double log_s[DFA_NUM_BOXES], log_f[DFA_NUM_BOXES];
    int pts = 0;

    for (b = 0; b < DFA_NUM_BOXES && DFA_BOXES[b] <= nn / 4; b++) {
        int s = DFA_BOXES[b];
        int num_segs = nn / s;
        if (num_segs == 0) continue;
        double f2_sum = 0.0;
        for (seg = 0; seg < num_segs; seg++) {
            int start = seg * s;
            double sx = 0, sy = 0, sxy = 0, sx2 = 0;
            for (i = 0; i < s; i++) {
                double xi = (double)i;
                sx += xi;
                sy += y[start + i];
                sxy += xi * y[start + i];
                sx2 += xi * xi;
            }
            double k = (double)s;
            double det = k * sx2 - sx * sx;
            if (fabs(det) < 1e-15) continue;
            double a0 = (sx2 * sy - sx * sxy) / det;
            double a1 = (k * sxy - sx * sy) / det;
            double resid = 0.0;
            for (i = 0; i < s; i++) {
                double d = y[start + i] - (a0 + a1 * (double)i);
                resid += d * d;
            }
            f2_sum += resid / k;
        }
        double f = sqrt(f2_sum / (double)num_segs);
        if (f > 0.0) {
            log_s[pts] = log((double)s);
            log_f[pts] = log(f);
            pts++;
        }
    }

    if (pts < 3) return result;

    double k = (double)pts;
    double sx = 0, sy = 0, sxy = 0, sx2 = 0;
    for (i = 0; i < pts; i++) {
        sx += log_s[i]; sy += log_f[i];
        sxy += log_s[i] * log_f[i]; sx2 += log_s[i] * log_s[i];
    }
    double slope = (k * sxy - sx * sy) / (k * sx2 - sx * sx);
    double ic = (sy - slope * sx) / k;
    double ym = sy / k;
    double sst = 0, ssr = 0;
    for (i = 0; i < pts; i++) {
        sst += (log_f[i] - ym) * (log_f[i] - ym);
        ssr += (log_f[i] - slope * log_s[i] - ic) * (log_f[i] - slope * log_s[i] - ic);
    }
    result.alpha = slope;
    result.r_squared = 1.0 - ssr / (sst > 1e-15 ? sst : 1e-15);
    return result;
}

#endif /* DFA_CORE_H */
