[book]
title = "Struktura"
description = "Time-series anomaly detection with no training data"
authors = ["Koscak Labs"]
language = "en"

[output.html]
git-repository-url = "https://github.com/koscak-labs/struktura"
