pub fn generate_c_monitor(window_size: usize, threshold: f64) -> String {
    format!(r#"/* dfa_monitor.c -- Generated by struktura codegen
 * Self-contained DFA structural health monitor.
 * Compile: gcc -Wall -Werror -O2 -lm -o dfa_monitor dfa_monitor.c
 * Zero dependencies. Pre-80s discipline.
 * https://github.com/koscak-labs/struktura
 */

#include <math.h>
#include <string.h>

#define DFA_WINDOW_SIZE {window}
#define DFA_THRESHOLD   {threshold:.4}
#define DFA_NUM_BOXES   6

static const int DFA_BOXES[DFA_NUM_BOXES] = {{16, 24, 36, 54, 81, 121}};

typedef struct {{
    double alpha;
    double r_squared;
}} dfa_result_t;

typedef struct {{
    double buffer[DFA_WINDOW_SIZE];
    int pos;
    int filled;
    double baseline_alpha;
    int baseline_set;
    int learning_count;
}} dfa_monitor_t;

static dfa_result_t dfa_compute(const double *values, int n) {{
    dfa_result_t result = {{0.5, 0.0}};
    if (n < 64) return result;

    double mean = 0.0;
    int i, seg, b;
    for (i = 0; i < n; i++) mean += values[i];
    mean /= (double)n;

    /* Cumulative profile */
    double y[DFA_WINDOW_SIZE];
    double cum = 0.0;
    for (i = 0; i < n; i++) {{
        cum += values[i] - mean;
        y[i] = cum;
    }}

    /* DFA: measure fluctuation at each box size */
    double log_s[DFA_NUM_BOXES], log_f[DFA_NUM_BOXES];
    int pts = 0;

    for (b = 0; b < DFA_NUM_BOXES && DFA_BOXES[b] <= n / 4; b++) {{
        int s = DFA_BOXES[b];
        int num_segs = n / s;
        if (num_segs == 0) continue;
        double f2_sum = 0.0;
        for (seg = 0; seg < num_segs; seg++) {{
            int start = seg * s;
            double sx = 0, sy = 0, sxy = 0, sx2 = 0;
            for (i = 0; i < s; i++) {{
                double xi = (double)i;
                sx += xi;
                sy += y[start + i];
                sxy += xi * y[start + i];
                sx2 += xi * xi;
            }}
            double k = (double)s;
            double det = k * sx2 - sx * sx;
            if (fabs(det) < 1e-15) continue;
            double a0 = (sx2 * sy - sx * sxy) / det;
            double a1 = (k * sxy - sx * sy) / det;
            double resid = 0.0;
            for (i = 0; i < s; i++) {{
                double d = y[start + i] - (a0 + a1 * (double)i);
                resid += d * d;
            }}
            f2_sum += resid / k;
        }}
        double f = sqrt(f2_sum / (double)num_segs);
        if (f > 0.0) {{
            log_s[pts] = log((double)s);
            log_f[pts] = log(f);
            pts++;
        }}
    }}

    if (pts < 3) return result;

    /* Log-log linear regression */
    double k = (double)pts;
    double sx = 0, sy = 0, sxy = 0, sx2 = 0;
    for (i = 0; i < pts; i++) {{
        sx += log_s[i]; sy += log_f[i];
        sxy += log_s[i] * log_f[i]; sx2 += log_s[i] * log_s[i];
    }}
    double slope = (k * sxy - sx * sy) / (k * sx2 - sx * sx);
    double ic = (sy - slope * sx) / k;
    double ym = sy / k;
    double sst = 0, ssr = 0;
    for (i = 0; i < pts; i++) {{
        sst += (log_f[i] - ym) * (log_f[i] - ym);
        ssr += (log_f[i] - slope * log_s[i] - ic) * (log_f[i] - slope * log_s[i] - ic);
    }}
    result.alpha = slope;
    result.r_squared = 1.0 - ssr / (sst > 1e-15 ? sst : 1e-15);
    return result;
}}

/* Initialize monitor */
static void dfa_monitor_init(dfa_monitor_t *m) {{
    memset(m, 0, sizeof(*m));
}}

/* Push a sample. Returns: 0=learning, 1=healthy, 2=watch, 3=warning, 4=critical */
static int dfa_monitor_push(dfa_monitor_t *m, double value) {{
    m->buffer[m->pos] = value;
    m->pos = (m->pos + 1) % DFA_WINDOW_SIZE;
    if (m->pos == 0) m->filled = 1;
    if (!m->filled) return 0;

    m->learning_count++;
    dfa_result_t r = dfa_compute(m->buffer, DFA_WINDOW_SIZE);

    /* Learning phase: first 10 windows establish baseline */
    if (!m->baseline_set && m->learning_count >= 10 && r.r_squared > 0.7) {{
        m->baseline_alpha = r.alpha;
        m->baseline_set = 1;
        return 0;
    }}
    if (!m->baseline_set) return 0;

    /* Health check */
    double shift = fabs(r.alpha - m->baseline_alpha);
    if (shift < DFA_THRESHOLD * 0.375) return 1; /* healthy */
    if (shift < DFA_THRESHOLD)         return 2; /* watch */
    if (shift < DFA_THRESHOLD * 1.875) return 3; /* warning */
    return 4; /* critical */
}}
"#, window = window_size, threshold = threshold)
}

pub fn generate_fprime_component(name: &str, window_size: usize) -> String {
    format!(r#"// {name}.fpp -- Generated F Prime DFA health monitor component
// Compile: fprime-util build
// Generated by: struktura codegen --fprime

module Svc {{
    passive component {name} {{

        sync input port schedIn: Svc.Sched

        guarded input port tlmIn: Fw.Tlm

        event StructuralShift(
            channelId: FwChanIdType
            baseline_alpha: F64
            current_alpha: F64
            delta: F64
        ) severity warning high \
          format "Channel {{}} structural shift: baseline={{.3f}} current={{.3f}} delta={{+.3f}}" \
          throttle 5

        event BaselineEstablished(
            channelId: FwChanIdType
            alpha: F64
            r_squared: F64
        ) severity activity high \
          format "Channel {{}} baseline: alpha={{.3f}} R2={{.4f}}"

        telemetry DfaAlpha: F64
        telemetry DfaR2: F64

        time get port timeCaller
        text event port logTextOut
        event port logOut
        telemetry port tlmOut
    }}
}}

// Link with libstruktura.a and include struktura.h
// Window size: {window}
// See: https://github.com/koscak-labs/struktura
"#, name = name, window = window_size)
}
