pub fn generate_c_monitor(window_size: usize, threshold: f64) -> String {
    format!(r#"/* dfa_monitor.c -- Generated by struktura codegen
 * Self-contained DFA structural health monitor.
 * Compile: gcc -Wall -Werror -O2 -lm -o dfa_monitor dfa_monitor.c
 * Zero dependencies. Pre-80s discipline.
 * https://github.com/koscak-labs/struktura
 */

#include <math.h>
#include <string.h>

#define DFA_WINDOW_SIZE {window}
#define DFA_THRESHOLD   {threshold:.4}
#define DFA_NUM_BOXES   6

static const int DFA_BOXES[DFA_NUM_BOXES] = {{16, 24, 36, 54, 81, 121}};

typedef struct {{
    double alpha;
    double r_squared;
}} dfa_result_t;

typedef struct {{
    double buffer[DFA_WINDOW_SIZE];
    int pos;
    int filled;
    double baseline_alpha;
    int baseline_set;
    int learning_count;
}} dfa_monitor_t;

static dfa_result_t dfa_compute(const double *values, int n) {{
    dfa_result_t result = {{0.5, 0.0}};
    if (n < 64) return result;

    double mean = 0.0;
    int i, seg, b;
    for (i = 0; i < n; i++) mean += values[i];
    mean /= (double)n;

    /* Cumulative profile */
    double y[DFA_WINDOW_SIZE];
    double cum = 0.0;
    for (i = 0; i < n; i++) {{
        cum += values[i] - mean;
        y[i] = cum;
    }}

    /* DFA: measure fluctuation at each box size */
    double log_s[DFA_NUM_BOXES], log_f[DFA_NUM_BOXES];
    int pts = 0;

    for (b = 0; b < DFA_NUM_BOXES && DFA_BOXES[b] <= n / 4; b++) {{
        int s = DFA_BOXES[b];
        int num_segs = n / s;
        if (num_segs == 0) continue;
        double f2_sum = 0.0;
        for (seg = 0; seg < num_segs; seg++) {{
            int start = seg * s;
            double sx = 0, sy = 0, sxy = 0, sx2 = 0;
            for (i = 0; i < s; i++) {{
                double xi = (double)i;
                sx += xi;
                sy += y[start + i];
                sxy += xi * y[start + i];
                sx2 += xi * xi;
            }}
            double k = (double)s;
            double det = k * sx2 - sx * sx;
            if (fabs(det) < 1e-15) continue;
            double a0 = (sx2 * sy - sx * sxy) / det;
            double a1 = (k * sxy - sx * sy) / det;
            double resid = 0.0;
            for (i = 0; i < s; i++) {{
                double d = y[start + i] - (a0 + a1 * (double)i);
                resid += d * d;
            }}
            f2_sum += resid / k;
        }}
        double f = sqrt(f2_sum / (double)num_segs);
        if (f > 0.0) {{
            log_s[pts] = log((double)s);
            log_f[pts] = log(f);
            pts++;
        }}
    }}

    if (pts < 3) return result;

    /* Log-log linear regression */
    double k = (double)pts;
    double sx = 0, sy = 0, sxy = 0, sx2 = 0;
    for (i = 0; i < pts; i++) {{
        sx += log_s[i]; sy += log_f[i];
        sxy += log_s[i] * log_f[i]; sx2 += log_s[i] * log_s[i];
    }}
    double slope = (k * sxy - sx * sy) / (k * sx2 - sx * sx);
    double ic = (sy - slope * sx) / k;
    double ym = sy / k;
    double sst = 0, ssr = 0;
    for (i = 0; i < pts; i++) {{
        sst += (log_f[i] - ym) * (log_f[i] - ym);
        ssr += (log_f[i] - slope * log_s[i] - ic) * (log_f[i] - slope * log_s[i] - ic);
    }}
    result.alpha = slope;
    result.r_squared = 1.0 - ssr / (sst > 1e-15 ? sst : 1e-15);
    return result;
}}

/* Initialize monitor */
static void dfa_monitor_init(dfa_monitor_t *m) {{
    memset(m, 0, sizeof(*m));
}}

/* Push a sample. Returns: 0=learning, 1=healthy, 2=watch, 3=warning, 4=critical */
static int dfa_monitor_push(dfa_monitor_t *m, double value) {{
    m->buffer[m->pos] = value;
    m->pos = (m->pos + 1) % DFA_WINDOW_SIZE;
    if (m->pos == 0) m->filled = 1;
    if (!m->filled) return 0;

    m->learning_count++;
    dfa_result_t r = dfa_compute(m->buffer, DFA_WINDOW_SIZE);

    /* Learning phase: first 10 windows establish baseline */
    if (!m->baseline_set && m->learning_count >= 10 && r.r_squared > 0.7) {{
        m->baseline_alpha = r.alpha;
        m->baseline_set = 1;
        return 0;
    }}
    if (!m->baseline_set) return 0;

    /* Health check */
    double shift = fabs(r.alpha - m->baseline_alpha);
    if (shift < DFA_THRESHOLD * 0.375) return 1; /* healthy */
    if (shift < DFA_THRESHOLD)         return 2; /* watch */
    if (shift < DFA_THRESHOLD * 1.875) return 3; /* warning */
    return 4; /* critical */
}}
"#, window = window_size, threshold = threshold)
}

pub fn generate_fprime_component(name: &str, window_size: usize) -> String {
    let mut s = String::with_capacity(1024);
    s.push_str(&format!("// {}.fpp -- Generated F Prime DFA health monitor\n", name));
    s.push_str("// Generated by: struktura codegen --fprime\n\n");
    s.push_str("module Svc {\n");
    s.push_str(&format!("    passive component {} {{\n\n", name));
    s.push_str("        sync input port schedIn: Svc.Sched\n");
    s.push_str("        guarded input port tlmIn: Fw.Tlm\n\n");
    s.push_str("        event StructuralShift(\n");
    s.push_str("            channelId: FwChanIdType\n");
    s.push_str("            baseline_alpha: F64\n");
    s.push_str("            current_alpha: F64\n");
    s.push_str("            delta: F64\n");
    s.push_str("        ) severity warning high\n\n");
    s.push_str("        event BaselineEstablished(\n");
    s.push_str("            channelId: FwChanIdType\n");
    s.push_str("            alpha: F64\n");
    s.push_str("            r_squared: F64\n");
    s.push_str("        ) severity activity high\n\n");
    s.push_str("        telemetry DfaAlpha: F64\n");
    s.push_str("        telemetry DfaR2: F64\n\n");
    s.push_str("        time get port timeCaller\n");
    s.push_str("        event port logOut\n");
    s.push_str("        telemetry port tlmOut\n");
    s.push_str("    }\n}\n\n");
    s.push_str(&format!("// Link with libstruktura.a, window size: {}\n", window_size));
    s.push_str("// https://github.com/koscak-labs/struktura\n");
    s
}

pub fn generate_cfs_app(name: &str, window_size: usize) -> String {
    let mut s = String::with_capacity(2048);
    s.push_str(&format!("/* {}_app.c -- Generated cFS DFA health monitor app\n", name.to_lowercase()));
    s.push_str(" * Generated by: struktura codegen --cfs\n");
    s.push_str(" * Link with libstruktura.a or embed dfa_monitor.c\n */\n\n");
    s.push_str("#include \"cfe.h\"\n");
    s.push_str("#include \"struktura.h\"\n\n");
    s.push_str(&format!("#define {}_WINDOW_SIZE {}\n\n", name.to_uppercase(), window_size));
    s.push_str("typedef struct {\n");
    s.push_str(&format!("    double buffer[{}_WINDOW_SIZE];\n", name.to_uppercase()));
    s.push_str("    uint32 pos;\n");
    s.push_str("    uint32 filled;\n");
    s.push_str("    double baseline;\n");
    s.push_str("    uint8 baseline_set;\n");
    s.push_str(&format!("}} {}_Data_t;\n\n", name));
    s.push_str(&format!("static {}_Data_t {}_Data;\n\n", name, name));
    s.push_str(&format!("void {}_Init(void) {{\n", name));
    s.push_str(&format!("    memset(&{}_Data, 0, sizeof({}_Data));\n", name, name));
    s.push_str("    CFE_EVS_SendEvent(1, CFE_EVS_EventType_INFORMATION,\n");
    s.push_str(&format!("        \"{} DFA health monitor initialized (window={})\");\n", name, window_size));
    s.push_str("}\n\n");
    s.push_str(&format!("void {}_ProcessSample(double value) {{\n", name));
    s.push_str(&format!("    {}_Data.buffer[{}_Data.pos] = value;\n", name, name));
    s.push_str(&format!("    {}_Data.pos = ({}_Data.pos + 1) % {}_WINDOW_SIZE;\n", name, name, name.to_uppercase()));
    s.push_str(&format!("    if ({}_Data.pos == 0) {}_Data.filled = 1;\n", name, name));
    s.push_str(&format!("    if (!{}_Data.filled) return;\n\n", name));
    s.push_str(&format!("    struktura_dfa_result_t r = struktura_dfa({}_Data.buffer, {}_WINDOW_SIZE);\n", name, name.to_uppercase()));
    s.push_str(&format!("    if (!{}_Data.baseline_set && r.r_squared > 0.7) {{\n", name));
    s.push_str(&format!("        {}_Data.baseline = r.alpha;\n", name));
    s.push_str(&format!("        {}_Data.baseline_set = 1;\n", name));
    s.push_str("        CFE_EVS_SendEvent(2, CFE_EVS_EventType_INFORMATION,\n");
    s.push_str("            \"DFA baseline established: alpha=%.3f R2=%.4f\", r.alpha, r.r_squared);\n");
    s.push_str("        return;\n    }\n");
    s.push_str(&format!("    if (!{}_Data.baseline_set) return;\n\n", name));
    s.push_str(&format!("    uint8_t verdict = struktura_health_check(r.alpha, {}_Data.baseline);\n", name));
    s.push_str("    if (verdict >= STRUKTURA_WARNING) {\n");
    s.push_str("        CFE_EVS_SendEvent(3, CFE_EVS_EventType_ERROR,\n");
    s.push_str(&format!("            \"{} structural shift: alpha=%.3f baseline=%.3f verdict=%d\",\n", name));
    s.push_str(&format!("            r.alpha, {}_Data.baseline, verdict);\n", name));
    s.push_str("    }\n}\n\n");
    s.push_str("// See: https://github.com/koscak-labs/struktura\n");
    s
}
